### ISSUE TITLE
Documentation? Still maintained?

### ISSUE THREAD

**Issue by VorpalBlade** [p-avital/keyed-set-rs#1]
This crate looks quite useful for something I'm doing (if it is still maintained). But I notice nothing in the public API is documented (or close to nothing anyway). That doesn't give me high hopes about this crate.

What is the status of this project?

**Comment by p-avital** [comment]
Considering it's used in Zenoh, it's not disappearing anytime soon, it's just that I've never needed to document it now make changes to it due to how small it is.

I'll try to make a documentation pass soon :)

**Comment by p-avital** [comment]
Hi there,

Just a quick ping to inform you that I've added a bit of documentation to the crate, updated its `hashbrown` dependency, and published its `1.0.0` version.

Enjoy :)

**Comment by VorpalBlade** [comment]
Thanks for taking the effort (and the quick response). 

Unfortunately I didn't end up using this crate in the end. While it did reduce memory usage, it turned out my problem was highly parallelisable (basically scaling with number of CPU cores, at least up to 24 cores it seems to scale perfectly), and I ended up using dashmap instead (taking the memory usage hit).
